// Auto-generated. Do not edit!

// (in-package abb_irb1200_planning.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class AbbGraspGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.grasp_id = null;
    }
    else {
      if (initObj.hasOwnProperty('grasp_id')) {
        this.grasp_id = initObj.grasp_id
      }
      else {
        this.grasp_id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AbbGraspGoal
    // Serialize message field [grasp_id]
    bufferOffset = _serializer.uint32(obj.grasp_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AbbGraspGoal
    let len;
    let data = new AbbGraspGoal(null);
    // Deserialize message field [grasp_id]
    data.grasp_id = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'abb_irb1200_planning/AbbGraspGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '120008ffefc83cc4fdc00d069e4bd8ad';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    uint32 grasp_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AbbGraspGoal(null);
    if (msg.grasp_id !== undefined) {
      resolved.grasp_id = msg.grasp_id;
    }
    else {
      resolved.grasp_id = 0
    }

    return resolved;
    }
};

module.exports = AbbGraspGoal;
