// Auto-generated. Do not edit!

// (in-package abb_irb1200_planning.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class AbbGraspResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_grasped = null;
    }
    else {
      if (initObj.hasOwnProperty('total_grasped')) {
        this.total_grasped = initObj.total_grasped
      }
      else {
        this.total_grasped = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type AbbGraspResult
    // Serialize message field [total_grasped]
    bufferOffset = _serializer.uint32(obj.total_grasped, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type AbbGraspResult
    let len;
    let data = new AbbGraspResult(null);
    // Deserialize message field [total_grasped]
    data.total_grasped = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'abb_irb1200_planning/AbbGraspResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '990752d94cb258b4f9a85c8e2c2cc9b3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 total_grasped
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new AbbGraspResult(null);
    if (msg.total_grasped !== undefined) {
      resolved.total_grasped = msg.total_grasped;
    }
    else {
      resolved.total_grasped = 0
    }

    return resolved;
    }
};

module.exports = AbbGraspResult;
