// Generated by gencpp from file abb_irb1200_planning/AbbGraspResult.msg
// DO NOT EDIT!


#ifndef ABB_IRB1200_PLANNING_MESSAGE_ABBGRASPRESULT_H
#define ABB_IRB1200_PLANNING_MESSAGE_ABBGRASPRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abb_irb1200_planning
{
template <class ContainerAllocator>
struct AbbGraspResult_
{
  typedef AbbGraspResult_<ContainerAllocator> Type;

  AbbGraspResult_()
    : total_grasped(0)  {
    }
  AbbGraspResult_(const ContainerAllocator& _alloc)
    : total_grasped(0)  {
  (void)_alloc;
    }



   typedef uint32_t _total_grasped_type;
  _total_grasped_type total_grasped;





  typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> const> ConstPtr;

}; // struct AbbGraspResult_

typedef ::abb_irb1200_planning::AbbGraspResult_<std::allocator<void> > AbbGraspResult;

typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspResult > AbbGraspResultPtr;
typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspResult const> AbbGraspResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator1> & lhs, const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_grasped == rhs.total_grasped;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator1> & lhs, const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abb_irb1200_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "990752d94cb258b4f9a85c8e2c2cc9b3";
  }

  static const char* value(const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x990752d94cb258b4ULL;
  static const uint64_t static_value2 = 0xf9a85c8e2c2cc9b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb_irb1200_planning/AbbGraspResult";
  }

  static const char* value(const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 total_grasped\n"
;
  }

  static const char* value(const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_grasped);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AbbGraspResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abb_irb1200_planning::AbbGraspResult_<ContainerAllocator>& v)
  {
    s << indent << "total_grasped: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_grasped);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABB_IRB1200_PLANNING_MESSAGE_ABBGRASPRESULT_H
