// Generated by gencpp from file abb_irb1200_planning/AbbGraspFeedback.msg
// DO NOT EDIT!


#ifndef ABB_IRB1200_PLANNING_MESSAGE_ABBGRASPFEEDBACK_H
#define ABB_IRB1200_PLANNING_MESSAGE_ABBGRASPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abb_irb1200_planning
{
template <class ContainerAllocator>
struct AbbGraspFeedback_
{
  typedef AbbGraspFeedback_<ContainerAllocator> Type;

  AbbGraspFeedback_()
    : percent_complete(0.0)  {
    }
  AbbGraspFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct AbbGraspFeedback_

typedef ::abb_irb1200_planning::AbbGraspFeedback_<std::allocator<void> > AbbGraspFeedback;

typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspFeedback > AbbGraspFeedbackPtr;
typedef boost::shared_ptr< ::abb_irb1200_planning::AbbGraspFeedback const> AbbGraspFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator1> & lhs, const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator1> & lhs, const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abb_irb1200_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb_irb1200_planning/AbbGraspFeedback";
  }

  static const char* value(const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percent_complete\n"
"\n"
;
  }

  static const char* value(const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AbbGraspFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abb_irb1200_planning::AbbGraspFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABB_IRB1200_PLANNING_MESSAGE_ABBGRASPFEEDBACK_H
