// Generated by gencpp from file abb_irb1200_planning/AbbPoseRequest.msg
// DO NOT EDIT!


#ifndef ABB_IRB1200_PLANNING_MESSAGE_ABBPOSEREQUEST_H
#define ABB_IRB1200_PLANNING_MESSAGE_ABBPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abb_irb1200_planning
{
template <class ContainerAllocator>
struct AbbPoseRequest_
{
  typedef AbbPoseRequest_<ContainerAllocator> Type;

  AbbPoseRequest_()
    : get_data_signal(0)  {
    }
  AbbPoseRequest_(const ContainerAllocator& _alloc)
    : get_data_signal(0)  {
  (void)_alloc;
    }



   typedef uint32_t _get_data_signal_type;
  _get_data_signal_type get_data_signal;





  typedef boost::shared_ptr< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AbbPoseRequest_

typedef ::abb_irb1200_planning::AbbPoseRequest_<std::allocator<void> > AbbPoseRequest;

typedef boost::shared_ptr< ::abb_irb1200_planning::AbbPoseRequest > AbbPoseRequestPtr;
typedef boost::shared_ptr< ::abb_irb1200_planning::AbbPoseRequest const> AbbPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator1> & lhs, const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.get_data_signal == rhs.get_data_signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator1> & lhs, const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace abb_irb1200_planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d8eb38d0e52d5a5bbac3df7c2d5155c";
  }

  static const char* value(const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d8eb38d0e52d5a5ULL;
  static const uint64_t static_value2 = 0xbbac3df7c2d5155cULL;
};

template<class ContainerAllocator>
struct DataType< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb_irb1200_planning/AbbPoseRequest";
  }

  static const char* value(const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# define the client request\n"
"uint32 get_data_signal\n"
;
  }

  static const char* value(const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get_data_signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AbbPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abb_irb1200_planning::AbbPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "get_data_signal: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.get_data_signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABB_IRB1200_PLANNING_MESSAGE_ABBPOSEREQUEST_H
