// Generated by gencpp from file abb_irb1200_planning/AbbPose.msg
// DO NOT EDIT!


#ifndef ABB_IRB1200_PLANNING_MESSAGE_ABBPOSE_H
#define ABB_IRB1200_PLANNING_MESSAGE_ABBPOSE_H

#include <ros/service_traits.h>


#include <abb_irb1200_planning/AbbPoseRequest.h>
#include <abb_irb1200_planning/AbbPoseResponse.h>


namespace abb_irb1200_planning
{

struct AbbPose
{

typedef AbbPoseRequest Request;
typedef AbbPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AbbPose
} // namespace abb_irb1200_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_irb1200_planning::AbbPose > {
  static const char* value()
  {
    return "2d90935736f98770c992f0655b381c24";
  }

  static const char* value(const ::abb_irb1200_planning::AbbPose&) { return value(); }
};

template<>
struct DataType< ::abb_irb1200_planning::AbbPose > {
  static const char* value()
  {
    return "abb_irb1200_planning/AbbPose";
  }

  static const char* value(const ::abb_irb1200_planning::AbbPose&) { return value(); }
};


// service_traits::MD5Sum< ::abb_irb1200_planning::AbbPoseRequest> should match
// service_traits::MD5Sum< ::abb_irb1200_planning::AbbPose >
template<>
struct MD5Sum< ::abb_irb1200_planning::AbbPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_irb1200_planning::AbbPose >::value();
  }
  static const char* value(const ::abb_irb1200_planning::AbbPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_irb1200_planning::AbbPoseRequest> should match
// service_traits::DataType< ::abb_irb1200_planning::AbbPose >
template<>
struct DataType< ::abb_irb1200_planning::AbbPoseRequest>
{
  static const char* value()
  {
    return DataType< ::abb_irb1200_planning::AbbPose >::value();
  }
  static const char* value(const ::abb_irb1200_planning::AbbPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_irb1200_planning::AbbPoseResponse> should match
// service_traits::MD5Sum< ::abb_irb1200_planning::AbbPose >
template<>
struct MD5Sum< ::abb_irb1200_planning::AbbPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_irb1200_planning::AbbPose >::value();
  }
  static const char* value(const ::abb_irb1200_planning::AbbPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_irb1200_planning::AbbPoseResponse> should match
// service_traits::DataType< ::abb_irb1200_planning::AbbPose >
template<>
struct DataType< ::abb_irb1200_planning::AbbPoseResponse>
{
  static const char* value()
  {
    return DataType< ::abb_irb1200_planning::AbbPose >::value();
  }
  static const char* value(const ::abb_irb1200_planning::AbbPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_IRB1200_PLANNING_MESSAGE_ABBPOSE_H
