; Auto-generated. Do not edit!


(cl:in-package abb_irb1200_planning-msg)


;//! \htmlinclude AbbGraspResult.msg.html

(cl:defclass <AbbGraspResult> (roslisp-msg-protocol:ros-message)
  ((total_grasped
    :reader total_grasped
    :initarg :total_grasped
    :type cl:integer
    :initform 0))
)

(cl:defclass AbbGraspResult (<AbbGraspResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AbbGraspResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AbbGraspResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name abb_irb1200_planning-msg:<AbbGraspResult> is deprecated: use abb_irb1200_planning-msg:AbbGraspResult instead.")))

(cl:ensure-generic-function 'total_grasped-val :lambda-list '(m))
(cl:defmethod total_grasped-val ((m <AbbGraspResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader abb_irb1200_planning-msg:total_grasped-val is deprecated.  Use abb_irb1200_planning-msg:total_grasped instead.")
  (total_grasped m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AbbGraspResult>) ostream)
  "Serializes a message object of type '<AbbGraspResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_grasped)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_grasped)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_grasped)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_grasped)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AbbGraspResult>) istream)
  "Deserializes a message object of type '<AbbGraspResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_grasped)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_grasped)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_grasped)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_grasped)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AbbGraspResult>)))
  "Returns string type for a message object of type '<AbbGraspResult>"
  "abb_irb1200_planning/AbbGraspResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AbbGraspResult)))
  "Returns string type for a message object of type 'AbbGraspResult"
  "abb_irb1200_planning/AbbGraspResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AbbGraspResult>)))
  "Returns md5sum for a message object of type '<AbbGraspResult>"
  "990752d94cb258b4f9a85c8e2c2cc9b3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AbbGraspResult)))
  "Returns md5sum for a message object of type 'AbbGraspResult"
  "990752d94cb258b4f9a85c8e2c2cc9b3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AbbGraspResult>)))
  "Returns full string definition for message of type '<AbbGraspResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_grasped~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AbbGraspResult)))
  "Returns full string definition for message of type 'AbbGraspResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_grasped~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AbbGraspResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AbbGraspResult>))
  "Converts a ROS message object to a list"
  (cl:list 'AbbGraspResult
    (cl:cons ':total_grasped (total_grasped msg))
))
